// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../components.plugin").default> &
  InjectionType<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/lib/vueuse-head.plugin").default> &
  InjectionType<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/plugin").default> &
  InjectionType<typeof import("../../../../../node_modules/nuxt/dist/app/plugins/router").default> &
  InjectionType<typeof import("../dist.plugin.3e91f4ad").default> &
  InjectionType<typeof import("../../../dist/runtime/plugins/plugin").default> &
  InjectionType<typeof import("../../../../schema/dist/runtime/plugins/store").default> &
  InjectionType<typeof import("../../../../schema/dist/runtime/plugins/plugin").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }
}

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
