// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'DruxtDebug': typeof import("../../../druxt/dist/runtime/components/DruxtDebug.vue")['default'],
    'DruxtDemo': typeof import("../../../druxt/dist/runtime/components/DruxtDemo.vue")['default'],
    'DruxtDemoComponent': typeof import("../../../druxt/dist/runtime/components/DruxtDemoComponent.vue")['default'],
    'DruxtMenu': typeof import("../../dist/runtime/components/DruxtMenu.vue")['default'],
    'DruxtMenuItem': typeof import("../../dist/runtime/components/DruxtMenuItem.vue")['default'],
    'DruxtMenuItemWrapper': typeof import("../../dist/runtime/components/DruxtMenuItemWrapper.vue")['default'],
    'DruxtMenuLink': typeof import("../../dist/runtime/components/DruxtMenuLink.vue")['default'],
    'DruxtMenuWrapper': typeof import("../../dist/runtime/components/DruxtMenuWrapper.vue")['default'],
    'NuxtWelcome': typeof import("../../../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../../../../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../../../../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyDruxtDebug': typeof import("../../../druxt/dist/runtime/components/DruxtDebug.vue")['default'],
    'LazyDruxtDemo': typeof import("../../../druxt/dist/runtime/components/DruxtDemo.vue")['default'],
    'LazyDruxtDemoComponent': typeof import("../../../druxt/dist/runtime/components/DruxtDemoComponent.vue")['default'],
    'LazyDruxtMenu': typeof import("../../dist/runtime/components/DruxtMenu.vue")['default'],
    'LazyDruxtMenuItem': typeof import("../../dist/runtime/components/DruxtMenuItem.vue")['default'],
    'LazyDruxtMenuItemWrapper': typeof import("../../dist/runtime/components/DruxtMenuItemWrapper.vue")['default'],
    'LazyDruxtMenuLink': typeof import("../../dist/runtime/components/DruxtMenuLink.vue")['default'],
    'LazyDruxtMenuWrapper': typeof import("../../dist/runtime/components/DruxtMenuWrapper.vue")['default'],
    'LazyNuxtWelcome': typeof import("../../../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../../../../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../../../../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const DruxtDebug: typeof import("../../../druxt/dist/runtime/components/DruxtDebug.vue")['default']
export const DruxtDemo: typeof import("../../../druxt/dist/runtime/components/DruxtDemo.vue")['default']
export const DruxtDemoComponent: typeof import("../../../druxt/dist/runtime/components/DruxtDemoComponent.vue")['default']
export const DruxtMenu: typeof import("../../dist/runtime/components/DruxtMenu.vue")['default']
export const DruxtMenuItem: typeof import("../../dist/runtime/components/DruxtMenuItem.vue")['default']
export const DruxtMenuItemWrapper: typeof import("../../dist/runtime/components/DruxtMenuItemWrapper.vue")['default']
export const DruxtMenuLink: typeof import("../../dist/runtime/components/DruxtMenuLink.vue")['default']
export const DruxtMenuWrapper: typeof import("../../dist/runtime/components/DruxtMenuWrapper.vue")['default']
export const NuxtWelcome: typeof import("../../../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../../../../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../../../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyDruxtDebug: typeof import("../../../druxt/dist/runtime/components/DruxtDebug.vue")['default']
export const LazyDruxtDemo: typeof import("../../../druxt/dist/runtime/components/DruxtDemo.vue")['default']
export const LazyDruxtDemoComponent: typeof import("../../../druxt/dist/runtime/components/DruxtDemoComponent.vue")['default']
export const LazyDruxtMenu: typeof import("../../dist/runtime/components/DruxtMenu.vue")['default']
export const LazyDruxtMenuItem: typeof import("../../dist/runtime/components/DruxtMenuItem.vue")['default']
export const LazyDruxtMenuItemWrapper: typeof import("../../dist/runtime/components/DruxtMenuItemWrapper.vue")['default']
export const LazyDruxtMenuLink: typeof import("../../dist/runtime/components/DruxtMenuLink.vue")['default']
export const LazyDruxtMenuWrapper: typeof import("../../dist/runtime/components/DruxtMenuWrapper.vue")['default']
export const LazyNuxtWelcome: typeof import("../../../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../../../../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../../../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
