# Basic LAMP stack
version: "2.1"
services:
  # Web
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: apache
    depends_on:
      - cli

  # DB
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mysql
  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    environment:
      - "XDEBUG_CONFIG=client_host=${DOCKSAL_HOST_IP} client_port=9000"
      - "XDEBUG_MODE=debug"
      - IS_DOCKSAL=true
      - PHP_IDE_CONFIG=serverName=${VIRTUAL_HOST}
      - NUXT_BASE_URL=${NUXT_BASE_URL}

  # Solr
  solr:
    image: docksal/solr:8.6-edge
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
